import { describe, expect, it } from "vitest";

import { renderAgentsMd } from "../src/core/doc-generator/renderers/render-agents-md";
import {
  buildGeneratedDocPaths,
  getTicketTemplateRelativePath,
} from "../src/core/models/generated-paths";
import { RepoContextSchema } from "../src/core/models/repo-context";
import { RepoRelativePathSchema } from "../src/core/models/generated-paths";

const repoContext = RepoContextSchema.parse({
  repoRoot: "/repo",
  generatedAt: "2026-05-01T00:00:00.000Z",
  stack: {
    framework: "Next.js",
    language: "TypeScript",
    packageManager: "pnpm",
    styling: ["Tailwind CSS"],
    validation: ["Zod"],
    database: ["Supabase"],
    testFramework: ["Vitest"],
  },
  commands: {
    dev: "pnpm dev",
    test: "pnpm test",
  },
  importantFiles: [
    {
      path: "README.md",
      reason: "Project overview",
    },
  ],
  generatedDocs: {
    ...buildGeneratedDocPaths(),
    ticketTemplatePath: RepoRelativePathSchema.parse(
      getTicketTemplateRelativePath(),
    ),
  },
});

describe("renderAgentsMd", () => {
  it("renders AGENTS-compatible markdown from repo-aware agent rules", () => {
    const markdown = renderAgentsMd({
      repoContext,
      agentRulesMarkdown: "## Project overview\n\nRules content.\n",
    });

    expect(markdown.startsWith("# AGENTS.md")).toBe(true);
    expect(markdown).toContain("Generated by Bridger");
    expect(markdown).toContain(buildGeneratedDocPaths().repoAnalysisPath);
    expect(markdown).toContain(buildGeneratedDocPaths().architecturePath);
    expect(markdown).toContain(buildGeneratedDocPaths().conventionsPath);
    expect(markdown).toContain(buildGeneratedDocPaths().businessLogicPath);
    expect(markdown).toContain(buildGeneratedDocPaths().testingPath);
    expect(markdown).toContain(buildGeneratedDocPaths().agentRulesPath);
    expect(markdown).toContain("## Project overview");
    expect(markdown).toContain("Rules content.");
    expect(markdown.endsWith("\n")).toBe(true);
  });

  it("rejects empty agent rules markdown", () => {
    expect(() =>
      renderAgentsMd({
        repoContext,
        agentRulesMarkdown: "   ",
      }),
    ).toThrow("Cannot render AGENTS.md from empty agent rules markdown.");
  });
});
