import { describe, expect, it } from "vitest";

import { renderAgentsMd } from "../src/core/context-builder/render-agents-md";
import { RepoContextSchema } from "../src/core/models/repo-context";
import { RepoRelativePathSchema } from "../src/core/models/paths";

const repoContext = RepoContextSchema.parse({
  repoRoot: "/repo",
  generatedAt: "2026-05-01T00:00:00.000Z",
  stack: {
    framework: "Next.js",
    language: "TypeScript",
    packageManager: "pnpm",
    styling: ["Tailwind CSS"],
    validation: ["Zod"],
    database: ["Supabase"],
    testFramework: ["Vitest"],
  },
  commands: {
    dev: "pnpm dev",
    test: "pnpm test",
  },
  importantFiles: [
    {
      path: "README.md",
      reason: "Project overview",
    },
  ],
  generatedDocs: {
    repoAnalysisPath: RepoRelativePathSchema.parse(
      ".bridger/generated/repo-analysis.md",
    ),
    architecturePath: RepoRelativePathSchema.parse(
      ".bridger/generated/architecture.md",
    ),
    conventionsPath: RepoRelativePathSchema.parse(
      ".bridger/generated/conventions.md",
    ),
    businessLogicPath: RepoRelativePathSchema.parse(
      ".bridger/generated/business-logic.md",
    ),
    testingPath: RepoRelativePathSchema.parse(".bridger/generated/testing.md"),
    agentRulesPath: RepoRelativePathSchema.parse(
      ".bridger/generated/agent-rules.md",
    ),
    ticketTemplatePath: RepoRelativePathSchema.parse(
      ".bridger/generated/ticket-template.md",
    ),
  },
});

describe("renderAgentsMd", () => {
  it("renders AGENTS-compatible markdown from repo-aware agent rules", () => {
    const markdown = renderAgentsMd({
      repoContext,
      agentRulesMarkdown: "## Project overview\n\nRules content.\n",
    });

    expect(markdown.startsWith("# AGENTS.md")).toBe(true);
    expect(markdown).toContain("Generated by Bridger");
    expect(markdown).toContain(".bridger/generated/repo-analysis.md");
    expect(markdown).toContain(".bridger/generated/architecture.md");
    expect(markdown).toContain(".bridger/generated/conventions.md");
    expect(markdown).toContain(".bridger/generated/business-logic.md");
    expect(markdown).toContain(".bridger/generated/testing.md");
    expect(markdown).toContain(".bridger/generated/agent-rules.md");
    expect(markdown).toContain("## Project overview");
    expect(markdown).toContain("Rules content.");
    expect(markdown.endsWith("\n")).toBe(true);
  });

  it("rejects empty agent rules markdown", () => {
    expect(() =>
      renderAgentsMd({
        repoContext,
        agentRulesMarkdown: "   ",
      }),
    ).toThrow("Cannot render AGENTS.md from empty agent rules markdown.");
  });
});
