import { RepoContextSchema, type RepoContext } from "../models/repo-context";

export type RenderAgentsMdInput = {
  repoContext: RepoContext;
  agentRulesMarkdown: string;
};

export function renderAgentsMd(input: RenderAgentsMdInput): string {
  const parsedRepoContext = RepoContextSchema.parse(input.repoContext);

  if (input.agentRulesMarkdown.trim().length === 0) {
    throw new Error("Cannot render AGENTS.md from empty agent rules markdown.");
  }

  const docs = parsedRepoContext.generatedDocs;
  const markdown = [
    "# AGENTS.md",
    "",
    "Generated by Bridger from repo-aware analysis.",
    "",
    "This file is intended to provide additional repository-specific instructions for coding agents.",
    "",
    "## Source documents",
    "",
    `- \`${docs.repoAnalysisPath}\``,
    `- \`${docs.architecturePath}\``,
    `- \`${docs.conventionsPath}\``,
    `- \`${docs.businessLogicPath}\``,
    `- \`${docs.testingPath}\``,
    `- \`${docs.agentRulesPath}\``,
    "",
    "---",
    "",
    input.agentRulesMarkdown,
  ].join("\n");

  return markdown.endsWith("\n") ? markdown : `${markdown}\n`;
}
