import type { GenerateAgentRulesDocInput } from "../../../models/agent-rules-doc";
import { GenerateAgentRulesDocInputSchema } from "../../../models/agent-rules-doc";
import { KNOWLEDGE_DOC_SPECS } from "../../../doc-generator/doc-specs";
import type { KnowledgeDocPrompt } from "../../../doc-generator/knowledge-doc-prompt";
import {
  formatCommands,
  formatDetectedStack,
  formatGroundingRules,
  formatImportantFiles,
  formatMarkdownOutputRules,
  formatRequiredSections,
} from "../shared/prompt-formatting";

function formatRepoContext(
  repoContext: GenerateAgentRulesDocInput["repoContext"],
): string {
  return [
    "## Repo root",
    repoContext.repoRoot,
    "",
    "## Generated at",
    repoContext.generatedAt,
    "",
    "## Detected stack",
    formatDetectedStack(repoContext.stack),
    "",
    "## Commands",
    formatCommands(repoContext.commands),
    "",
    "## Important files",
    formatImportantFiles(repoContext.importantFiles),
  ].join("\n");
}

function formatGeneratedDocs(
  generatedDocs: GenerateAgentRulesDocInput["generatedDocs"],
): string {
  return [
    `## ${KNOWLEDGE_DOC_SPECS.repoAnalysis.filename}`,
    generatedDocs.repoAnalysis,
    "",
    `## ${KNOWLEDGE_DOC_SPECS.architecture.filename}`,
    generatedDocs.architecture,
    "",
    `## ${KNOWLEDGE_DOC_SPECS.conventions.filename}`,
    generatedDocs.conventions,
    "",
    `## ${KNOWLEDGE_DOC_SPECS.businessLogic.filename}`,
    generatedDocs.businessLogic,
    "",
    `## ${KNOWLEDGE_DOC_SPECS.testing.filename}`,
    generatedDocs.testing,
  ].join("\n");
}

export function buildAgentRulesPrompt(
  input: GenerateAgentRulesDocInput,
): KnowledgeDocPrompt {
  const parsedInput = GenerateAgentRulesDocInputSchema.parse(input);

  return {
    system: [
      "You are a senior software engineering lead writing repository-specific operating instructions for AI coding agents.",
      "",
      "Your task is to generate `agent-rules.md`: practical rules that help coding agents work safely and effectively in this specific repository.",
      "",
      "This document is not a generic AI coding policy. It should translate the generated repo knowledge into direct instructions that agents can follow before and during implementation.",
      "",
      "Primary questions this document must answer:",
      "1. What should an AI coding agent always do before modifying this repo?",
      "2. What repo-specific rules should the agent follow when changing architecture, business logic, UI, tests, or data access?",
      "3. What files, folders, or domains should the agent avoid touching unless explicitly requested?",
      "4. How should the agent scope changes to avoid overreach?",
      "5. What uncertainties should cause the agent to ask for clarification or mark assumptions explicitly?",
      "",
      "Critical rules:",
      "- Use only the provided repo context and generated documentation.",
      "- Do not invent repository rules, commands, domains, workflows, or risky areas.",
      "- Treat generated docs as context, but preserve their uncertainty. If a generated doc says something is unknown, do not turn it into a fact.",
      "- Prefer concrete repo-specific instructions over generic coding-agent advice.",
      "- Reference real files, folders, generated docs, or repo paths when giving non-trivial rules.",
      "- Include commands exactly as provided in repo context or generated docs. Do not invent commands.",
      "- Distinguish hard rules from recommendations and unknowns.",
      "- Do not include implementation plans, tickets, or refactoring proposals.",
      "- Do not mention these instructions or say that you are an AI.",
    ].join("\n"),

    prompt: [
      "# Task",
      "Generate practical, repo-specific rules for coding agents.",
      "",
      "# Required sections",
      formatRequiredSections(KNOWLEDGE_DOC_SPECS.agentRules.requiredSections),
      "",
      "# Section requirements:",
      "",
      "## Project overview",
      "- Provide a short repo-specific overview for coding agents.",
      "- Base it on the generated repo-analysis, architecture, and business-logic docs.",
      "- If the project purpose is unclear, say `Unknown`.",
      "- Do not write a generic project description.",
      "",
      "## Commands",
      "- List commands that agents may use for install, dev, build, lint, typecheck, test, or format.",
      "- Use commands exactly as they appear in repo context or generated docs.",
      "- Do not invent commands.",
      "- If a command category is missing, say it was not detected.",
      "- Briefly explain when each available command should be used.",
      "",
      "## Rules for agents",
      "- List direct operating rules agents should follow in this repo.",
      "- Rules should be practical and repo-specific.",
      "- Prefer rules tied to observed architecture, conventions, business logic, testing expectations, or risky areas.",
      "- Each rule should be phrased as an instruction.",
      "- Avoid generic rules unless they are made repo-specific with evidence.",
      "",
      "## Coding conventions",
      "- Summarize the most important coding conventions agents must follow.",
      "- Use the generated conventions document as the main source.",
      "- Include TypeScript, component, validation, styling, data access, server/client boundary, naming, and testing conventions when evidenced.",
      "- Preserve uncertainty when conventions are weakly evidenced.",
      "- Do not invent team preferences.",
      "",
      "## Business logic boundaries",
      "- Summarize the domain/business areas agents should treat carefully.",
      "- Use the generated business-logic document as the main source.",
      "- Identify files, folders, concepts, or workflows that represent business rules or domain behavior.",
      "- Tell agents when they should avoid changing business logic unless explicitly requested.",
      "- Preserve assumptions and unknowns from the business-logic document.",
      "",
      "## Testing expectations",
      "- Summarize how agents should verify changes in this repo.",
      "- Use the generated testing document as the main source.",
      "- Include when to add unit, integration, regression, component/UI, or manual QA checks when evidenced or recommended.",
      "- Mention commands exactly as provided.",
      "- If test evidence is weak or missing, say so and provide cautious verification guidance.",
      "",
      "## Risky areas",
      "- List repo-specific areas where agents should be cautious.",
      "- Base this on generated architecture, business-logic, conventions, and testing docs.",
      "- Include why each area is risky and the files/folders involved.",
      "- Examples may include central app entry points, domain/business logic, data access, schema files, generated files, ambiguous boundaries, or missing tests, but only include those supported by the provided docs.",
      "",
      "## Task scoping rules",
      "- Define how agents should keep implementation work scoped.",
      "- Include rules about inspecting relevant files before editing, avoiding unrelated refactors, minimizing dependency changes, preserving existing patterns, and documenting assumptions.",
      "- Make the rules specific to this repo where possible.",
      "- Include when the agent should ask for clarification or stop and report uncertainty.",
      "",
      "## Files/folders to avoid unless explicitly requested",
      "- List files or folders agents should not modify casually.",
      "- Include generated folders, central config, risky domain areas, data/schema files, or agent instruction files only when supported by the provided docs or repo context.",
      "- For each item, explain why it should be avoided.",
      "- If there is insufficient evidence to name avoid-list paths, say `Unknown` and provide general caution.",
      "",
      "## Unknowns",
      "- List uncertainties that agents should preserve when working in this repo.",
      "- Include unknowns about architecture, business logic, testing, data flow, external integrations, deployment, commands, or team conventions when present in the generated docs.",
      "- Phrase unknowns as practical warnings for future agent behavior.",
      "",
      "Style requirements:",
      "- Be concise and practical.",
      "- Use bullets where useful.",
      "- Use labels like `Rule:`, `Evidence:`, `Recommendation:`, and `Unknown:` where helpful.",
      "- Reference real file paths or generated docs in backticks.",
      "- Avoid generic filler.",
      "- Avoid confident claims without evidence.",
      "- Do not include code blocks unless absolutely necessary.",
      "",
      "# Grounding rules",
      formatGroundingRules(),
      "",
      "# Output rules",
      formatMarkdownOutputRules(),
      "",
      "# Repo context",
      formatRepoContext(parsedInput.repoContext),
      "",
      "# Generated docs",
      formatGeneratedDocs(parsedInput.generatedDocs),
      "",
    ].join("\n"),
  };
}
