import type { GenerateAgentRulesDocInput } from "../../../models/agent-rules-doc";
import { GenerateAgentRulesDocInputSchema } from "../../../models/agent-rules-doc";
import { KNOWLEDGE_DOC_SPECS } from "../../../doc-generator/doc-specs";
import type { KnowledgeDocPrompt } from "../../../doc-generator/knowledge-doc-prompt";
import {
  formatCommands,
  formatDetectedStack,
  formatGroundingRules,
  formatImportantFiles,
  formatMarkdownOutputRules,
} from "../shared/prompt-formatting";

function formatRepoContext(
  repoContext: GenerateAgentRulesDocInput["repoContext"],
): string {
  return [
    "## Repo root",
    repoContext.repoRoot,
    "",
    "## Generated at",
    repoContext.generatedAt,
    "",
    "## Detected stack",
    formatDetectedStack(repoContext.stack),
    "",
    "## Commands",
    formatCommands(repoContext.commands),
    "",
    "## Important files",
    formatImportantFiles(repoContext.importantFiles),
  ].join("\n");
}

function formatGeneratedDocs(
  generatedDocs: GenerateAgentRulesDocInput["generatedDocs"],
): string {
  return [
    `## ${KNOWLEDGE_DOC_SPECS.repoAnalysis.filename}`,
    generatedDocs.repoAnalysis,
    "",
    `## ${KNOWLEDGE_DOC_SPECS.architecture.filename}`,
    generatedDocs.architecture,
    "",
    `## ${KNOWLEDGE_DOC_SPECS.conventions.filename}`,
    generatedDocs.conventions,
    "",
    `## ${KNOWLEDGE_DOC_SPECS.businessLogic.filename}`,
    generatedDocs.businessLogic,
    "",
    `## ${KNOWLEDGE_DOC_SPECS.testing.filename}`,
    generatedDocs.testing,
  ].join("\n");
}

export function buildAgentRulesPrompt(
  input: GenerateAgentRulesDocInput,
): KnowledgeDocPrompt {
  const parsedInput = GenerateAgentRulesDocInputSchema.parse(input);

  return {
    system: [
      "You are a senior software engineering lead writing repository-specific operating instructions for AI coding agents.",
      "",
      "Your task is to generate `agent-rules.md`: a compact operating manual that tells AI coding agents how to work safely and effectively in this repository.",
      "",
      "The goal is not to create a generic coding-agent policy. The goal is to translate the generated repo knowledge into direct, repo-specific rules that improve future implementation work.",
      "",
      "This document should help an AI coding agent answer:",
      "1. What should I inspect before making a change?",
      "2. Which repo-specific patterns and boundaries must I preserve?",
      "3. What changes are risky or out of scope unless explicitly requested?",
      "4. How should I verify my work using commands that actually exist?",
      "5. What uncertainty should I preserve instead of turning into assumptions?",
      "",
      "Critical rules:",
      "- Use only the provided repo context and generated documentation.",
      "- Do not invent repository rules, commands, domains, workflows, files, folders, or risky areas.",
      "- Treat generated docs as context, but preserve their uncertainty. If a generated doc says something is unknown or weakly evidenced, do not turn it into a fact.",
      "- Synthesize operating rules; do not create a summary of every generated document.",
      "- Prefer direct repo-specific instructions over generic coding-agent advice.",
      "- Mention file paths only when they are directly useful for inspection, editing boundaries, or avoid-rules.",
      "- Do not cite a path or generated doc for every rule.",
      "- Include commands exactly as provided in repo context or generated docs. Do not invent commands.",
      "- Separate hard rules, cautious recommendations, and unknowns.",
      "- Keep the rules actionable during implementation.",
      "- Do not include implementation plans, tickets, or refactoring proposals.",
      "- Do not mention these instructions or say that you are an AI.",
    ].join("\n"),

    prompt: [
      "# Task",
      "Generate `agent-rules.md` for this repository.",
      "",
      "Write this as a concise, human-readable operating manual for coding agents.",
      "",
      "Do not optimize for exhaustive Markdown structure. Optimize for rules that prevent bad edits and improve implementation quality.",
      "",
      "# Output shape",
      "Use these sections, but keep them compact and merge subpoints when useful:",
      "",
      "## Agent operating principles",
      "Start with the most important repo-specific rules agents should follow before and during implementation.",
      "",
      "Focus on instructions such as:",
      "- inspect relevant existing code before editing;",
      "- preserve visible architecture and conventions;",
      "- avoid broad refactors unless explicitly requested;",
      "- keep changes scoped to the ticket;",
      "- preserve uncertainty from the generated docs;",
      "- prefer existing repo primitives over new abstractions or dependencies.",
      "",
      "Avoid generic rules unless they are made specific to this repository.",
      "",
      "## Repo-specific change boundaries",
      "Explain the boundaries agents should respect when modifying this repository.",
      "",
      "Cover boundaries that are supported by the generated docs, such as:",
      "- app entry points versus reusable/core logic;",
      "- CLI command layer versus core implementation modules;",
      "- server/client boundaries;",
      "- validation and schema boundaries;",
      "- data access or persistence boundaries;",
      "- business/domain behavior boundaries;",
      "- generated outputs and agent documentation;",
      "- tests and fixtures versus production code.",
      "",
      "If a boundary is unclear, describe the practical risk instead of inventing a rule.",
      "",
      "## Where to inspect before editing",
      "List the most important areas an agent should inspect before changing behavior.",
      "",
      "This is one of the few sections where file paths are especially useful. Include paths only when the generated docs or repo context make them actionable.",
      "",
      "For each entry, explain what kind of change requires inspecting it first.",
      "",
      "If there is not enough evidence to name concrete paths, give cautious inspection guidance without inventing paths.",
      "",
      "## Coding rules to preserve",
      "Summarize the conventions that matter most during implementation.",
      "",
      "Include TypeScript, component, validation, styling, data-access, server/client, naming, testing, and organization rules only when supported by the generated docs.",
      "",
      "Prefer direct instructions:",
      "- Put new code where similar code already lives.",
      "- Reuse existing schemas or validation patterns before adding new ones.",
      "- Follow existing component composition and styling patterns.",
      "- Keep server-only and client-side concerns separated when the repo shows that boundary.",
      "",
      "Do not turn weak conventions into hard rules.",
      "",
      "## Business logic and side-effect rules",
      "Explain how agents should handle product/domain behavior and side effects.",
      "",
      "Focus on rules that prevent accidental behavior changes:",
      "- preserve domain invariants and lifecycle behavior when visible;",
      "- inspect business-logic or data-access modules before changing behavior;",
      "- treat auth, billing, persistence, external services, background jobs, LLM calls, email, storage, analytics, telephony, or other side effects carefully when evidenced;",
      "- avoid inventing product requirements from names alone.",
      "",
      "If business logic is weakly evidenced, say what agents should not assume.",
      "",
      "## Verification rules",
      "List the commands and checks agents should use to verify changes.",
      "",
      "Use commands exactly as provided by repo context.",
      "",
      "Explain when to run each available command. If test evidence is weak, say so and give cautious verification guidance.",
      "",
      "Do not invent unavailable commands, CI behavior, coverage requirements, or QA processes.",
      "",
      "## Risky changes and avoid-rules",
      "List repo-specific changes agents should avoid unless explicitly requested.",
      "",
      "Examples:",
      "- broad architecture refactors;",
      "- introducing new dependencies where existing primitives exist;",
      "- changing central config or generated files casually;",
      "- modifying domain, validation, persistence, auth, billing, or side-effect behavior without inspecting related modules;",
      "- mixing server/client concerns where the repo shows a boundary;",
      "- claiming tests or conventions exist when evidence is weak.",
      "",
      "Only include avoid-rules supported by generated docs or meaningful unknowns.",
      "",
      "## Task scoping rules",
      "Define how agents should keep implementation work narrow.",
      "",
      "Include practical instructions:",
      "- make the smallest change that satisfies the ticket;",
      "- do not fix unrelated issues while implementing a task;",
      "- do not rename, reorganize, or restyle unrelated code;",
      "- do not add new tools or dependencies without explicit request;",
      "- document assumptions when context is incomplete;",
      "- ask for clarification or stop when a change depends on unknown product behavior.",
      "",
      "Make these rules specific to this repo where the generated docs provide enough context.",
      "",
      "## Unknowns agents must preserve",
      "List uncertainties from the generated docs that future agents should not collapse into facts.",
      "",
      "Good entries:",
      "- architecture boundaries are only partially visible;",
      "- data flow or persistence ownership is unclear;",
      "- product/domain workflows are weakly evidenced;",
      "- testing conventions or coverage expectations are not visible;",
      "- external integrations or side effects are suggested but not fully represented;",
      "- team preferences are not documented.",
      "",
      "Phrase unknowns as practical warnings for future implementation work.",
      "",
      "# Style rules",
      "- Write plain Markdown.",
      "- Be compact and practical.",
      "- Prefer short paragraphs and focused bullets.",
      "- Avoid decorative Markdown.",
      "- Avoid bold and italic unless essential.",
      "- Do not summarize every generated doc.",
      "- Do not include an evidence trail.",
      "- Do not use `Rule:`, `Evidence:`, `Recommendation:`, and `Unknown:` labels for every bullet.",
      "- Do not cite file paths or generated docs after every claim.",
      "- Mention a path only when it helps the agent know where to inspect, edit carefully, or avoid changes.",
      "- Mention commands exactly as they appear in repo context.",
      "- Avoid generic coding-agent filler.",
      "- Prefer fewer, stronger operating rules.",
      "- Use cautious language when evidence is weak: `appears to`, `likely`, `unclear`, `not visible from the selected context`.",
      "- Do not include code blocks unless absolutely necessary.",
      "",
      "# Grounding rules",
      formatGroundingRules(),
      "",
      "# Output rules",
      formatMarkdownOutputRules(),
      "",
      "# Repo context",
      formatRepoContext(parsedInput.repoContext),
      "",
      "# Generated docs",
      formatGeneratedDocs(parsedInput.generatedDocs),
      "",
    ].join("\n"),
  };
}
