import type { KnowledgeDocGenerationInput } from "../../../doc-generator/knowledge-doc-input";
import type { KnowledgeDocPrompt } from "../../../doc-generator/knowledge-doc-prompt";
import { KNOWLEDGE_DOC_SPECS } from "../../../doc-generator/doc-specs";
import {
  formatGroundingRules,
  formatKnowledgeDocContext,
  formatMarkdownOutputRules,
  formatRequiredSections,
} from "../shared/prompt-formatting";

export function buildArchitecturePrompt(
  input: KnowledgeDocGenerationInput,
): KnowledgeDocPrompt {
  return {
    system: [
      "You are a senior software architect working for Bridger, a tool that prepares repositories for AI coding agents.",
      "",
      "Your task is to generate `architecture.md`: a grounded guide to the repository structure, major layers, data flow, commands, and risky areas represented in the codebase.",
      "",
      "This document is not a generic summary. It should help AI coding agents understand how the repository is organized before changing code.",
      "",
      "Primary questions this document must answer:",
      "1. How is the repository structured?",
      "2. What are the major layers, folders, and entry points?",
      "3. What commands or flows are visible from the repo context?",
      "4. What areas look risky or central to the app?",
      "5. What architecture assumptions should an agent avoid making without more evidence?",
      "",
      "Critical rules:",
      "- Use only the provided repository context, file index summary, and important file excerpts.",
      "- Do not invent architecture layers, workflows, data flow, commands, or risky areas.",
      "- Treat source code and selected file excerpts as stronger evidence than README/docs.",
      "- Treat names of files/folders as clues, not proof, unless supported by code content.",
      "- Distinguish observed facts from assumptions and unknowns.",
      "- Reference real files and folders in backticks when making architecture claims.",
      "- Prefer practical repo understanding over generic architecture language.",
      "- Do not summarize every file.",
      "- Do not write implementation plans, refactoring suggestions, or tickets.",
      "- Do not mention these instructions or say that you are an AI.",
    ].join("\n"),
    prompt: [
      "# Task",
      "Generate `architecture.md` for this repository.",
      "",
      "The document must be valid Markdown and must include exactly these top-level sections, in this order:",
      "",
      "# Required sections",
      formatRequiredSections(KNOWLEDGE_DOC_SPECS.architecture.requiredSections),
      "",
      "# Section requirements:",
      "",
      "## Project overview",
      "- Explain what the repository appears to be, only if evidence supports it.",
      "- If the purpose is unclear, say `Unknown`.",
      "- Mention the strongest evidence files or folders.",
      "- Keep this concise and evidence-based.",
      "",
      "## Detected stack",
      "- Summarize the detected framework, language, package manager, styling, validation, database, and testing tools from repo context.",
      "- Do not infer missing technologies from vague filenames.",
      "- If a stack category is empty or `unknown`, state that it was not detected.",
      "- Mention evidence from repo context and file index only when relevant.",
      "",
      "## App structure",
      "- Describe the visible repo structure and major folders.",
      "- Focus on entry points, app code, components, lib/helpers, generated output, docs, tests, and config areas.",
      "- Explain why each area matters.",
      "- If the structure is unclear, say so.",
      "",
      "## Core domains",
      "- Identify visible application areas or domain folders only when they are directly evidenced.",
      "- Mention any clear business areas, feature modules, or operational domains.",
      "- Reference evidence paths.",
      "- If no domains are visible, say `Unknown`.",
      "",
      "## Important folders",
      "- List the most useful folders for later prompts to inspect.",
      "- Focus on folders that reveal app entry points, domain logic, models, tests, or generated output.",
      "- Use concise bullets and explain why each matters.",
      "",
      "## Data flow assumptions",
      "- Describe the visible flow of data through the repo only when it can be supported by code or file layout.",
      "- If data flow is unclear, say `Unknown`.",
      "- Separate observed flow from assumptions.",
      "",
      "## Commands",
      "- List commands that agents may use for install, dev, build, lint, typecheck, test, or format.",
      "- Use commands exactly as they appear in repo context or generated docs.",
      "- If a command category is missing, say it was not detected.",
      "- Briefly explain when each available command should be used.",
      "",
      "## Risky areas",
      "- List repo-specific areas where agents should be cautious.",
      "- Base this on visible structure and evidence.",
      "- Include why each area is risky and the files/folders involved.",
      "",
      "## Unknowns",
      "- List gaps in architectural evidence that future coding agents should not assume.",
      "- Include unknowns about structure, boundaries, commands, data flow, and generated files when evidence is absent.",
      "- Make these unknowns practical for future implementation work.",
      "",
      "Style requirements:",
      "- Be concise and practical.",
      "- Use bullets where useful.",
      "- Use labels like `Observed:`, `Evidence:`, `Assumption:`, `Unknown:`, and `Confidence:`.",
      "- Reference real file paths in backticks.",
      "- Avoid generic filler.",
      "- Avoid confident claims without file evidence.",
      "- Do not include code blocks unless absolutely necessary.",
      "",
      "# Grounding rules",
      formatGroundingRules(),
      "",
      "# Output rules",
      formatMarkdownOutputRules(),
      "",
      "# Repo context",
      formatKnowledgeDocContext(input),
    ].join("\n"),
  };
}
