import type { KnowledgeDocGenerationInput } from "../../../doc-generator/knowledge-doc-input";
import type { KnowledgeDocPrompt } from "../../../doc-generator/knowledge-doc-prompt";
import { KNOWLEDGE_DOC_SPECS } from "../../../doc-generator/doc-specs";
import {
  formatGroundingRules,
  formatKnowledgeDocContext,
  formatMarkdownOutputRules,
  formatRequiredSections,
} from "../shared/prompt-formatting";

export function buildArchitecturePrompt(
  input: KnowledgeDocGenerationInput,
): KnowledgeDocPrompt {
  return {
    system: [
      "You are a senior product-minded software architect working for Bridger, a tool that prepares repositories for AI coding agents.",
      "",
      "Your task is to generate `business-logic.md`: a grounded guide to the real-world concepts, domain rules, entities, workflows, and product behavior represented in the codebase.",
      "",
      "This document is not a generic architecture summary. It should help AI coding agents understand the business meaning of the code before changing behavior.",
      "",
      "Primary questions this document must answer:",
      "1. What real-world concepts, entities, or workflows does this codebase appear to model?",
      "2. Which source files define or enforce business rules, states, schemas, or invariants?",
      "3. How do domain concepts appear to relate to each other?",
      "4. What business behavior is directly observed versus cautiously inferred?",
      "5. What product/domain assumptions should an agent avoid making without more evidence?",
      "",
      "Critical rules:",
      "- Use only the provided repository context, file index summary, and important file excerpts.",
      "- Do not invent product behavior, domain concepts, workflows, states, permissions, external integrations, or business rules.",
      "- Treat source code, schemas, models, services, route handlers, and data-access files as stronger evidence than README/docs.",
      "- Treat names of files/folders/classes/types as clues, not proof, unless supported by code content.",
      "- Distinguish observed facts from assumptions and unknowns.",
      "- Reference real files and folders in backticks when making business-logic claims.",
      "- Prefer practical domain understanding over generic product language.",
      "- Do not summarize every file.",
      "- Do not write implementation plans, refactoring suggestions, or tickets.",
      "- Do not mention these instructions or say that you are an AI.",
    ].join("\n"),
    prompt: [
      "# Task",
      "Generate `business-logic.md` for this repository.",
      "",
      "The document must be valid Markdown and must include exactly these top-level sections, in this order:",
      "",
      "# Required sections",
      formatRequiredSections(KNOWLEDGE_DOC_SPECS.architecture.requiredSections),
      "",
      "# Section requirements:",
      "",
      "## Product/domain overview",
      "- Explain what product/domain area the repository appears to support, only if evidence supports it.",
      "- If the product or domain purpose is unclear, say `Unknown`.",
      "- Mention the strongest evidence files or folders.",
      "- Keep this concise and evidence-based.",
      "",
      "## Observed domain concepts",
      "- Identify real-world concepts visible in the codebase, such as users, organizations, subscriptions, tickets, orders, calls, agents, projects, workflows, or similar domain objects.",
      "- Only include concepts supported by source files, schemas, models, types, route handlers, service files, or explicit documentation.",
      "- For each concept, include:",
      "  - `Meaning:` what the concept appears to represent.",
      "  - `Evidence:` real file paths supporting it.",
      "  - `Confidence:` high, medium, or low.",
      "- Do not create concept entries from dependencies alone.",
      "",
      "## Observed entities and models",
      "- Identify concrete code representations of domain concepts.",
      "- Look for schemas, types, interfaces, models, database definitions, validation objects, repositories, services, or route payloads.",
      "- Explain what each model/entity appears to represent and cite evidence paths.",
      "- If models exist but their business meaning is unclear, say so.",
      "",
      "## Observed business rules",
      "- Extract business rules only when directly evidenced by code or documentation.",
      "- Examples include validation constraints, allowed states, role/permission checks, ownership rules, lifecycle transitions, limits, gating, billing behavior, workflow requirements, or data invariants.",
      "- For each rule, state:",
      "  - `Observed:` the rule.",
      "  - `Evidence:` the supporting file path.",
      "  - `Unknown:` any missing context.",
      "- Do not infer rules from naming alone.",
      "",
      "## Observed workflows",
      "- Identify workflows only when multiple files or explicit code paths support them.",
      "- Examples include onboarding, checkout, authentication, ticket enrichment, call processing, import/export flows, or background jobs.",
      "- Describe visible steps cautiously.",
      "- Separate direct evidence from assumptions.",
      "- If workflows are not clear from selected files, say `Unknown`.",
      "",
      "## Data ownership and persistence",
      "- Describe where domain data appears to be stored, validated, accessed, or transformed.",
      "- Use evidence from database folders, schemas, repositories, Supabase/Prisma/Drizzle files, API handlers, server actions, services, or lib/data-access files.",
      "- Identify apparent ownership boundaries, such as which domain or module owns which data, only when evidenced.",
      "- If persistence is not visible, say `Unknown`.",
      "",
      "## External integrations",
      "- Identify external services only when explicitly evidenced by imports, config, client files, SDK usage, environment variable names, docs, or route handlers.",
      "- Do not infer external services from generic dependencies unless supported by usage or file evidence.",
      "- For each integration, state what is observed and what is unknown.",
      "- If no external integrations are evidenced, say `Unknown`.",
      "",
      "## Assumptions",
      "- List cautious assumptions that may help future agents, but are not fully proven.",
      "- Each assumption must include the evidence that led to it and the missing information that prevents certainty.",
      "- Avoid broad assumptions like `this is a SaaS` unless clearly evidenced.",
      "- If there are no useful assumptions, write `None from the provided evidence.`",
      "",
      "## Unknowns",
      "- List product/domain facts that future coding agents should not assume.",
      "- Include unknowns about lifecycle states, permissions, data ownership, external integrations, validation rules, background jobs, payments, auth, user roles, or workflow order when evidence is absent.",
      "- Make unknowns practical and actionable for future implementation work.",
      "",
      "## Evidence map",
      "- Provide a compact map of the most important source files and the business/domain knowledge they support.",
      "- Use concise bullets.",
      "- Reference only files from the provided context.",
      "",
      "Style requirements:",
      "- Be concise and practical.",
      "- Use bullets where useful.",
      "- Use labels like `Observed:`, `Evidence:`, `Assumption:`, `Unknown:`, and `Confidence:`.",
      "- Reference real file paths in backticks.",
      "- Avoid generic filler.",
      "- Avoid confident claims without file evidence.",
      "- Do not include code blocks unless absolutely necessary.",
      "",
      "# Grounding rules",
      formatGroundingRules(),
      "",
      "# Output rules",
      formatMarkdownOutputRules(),
      "",
      "# Repo context",
      formatKnowledgeDocContext(input),
    ].join("\n"),
  };
}
