import type { KnowledgeDocGenerationInput } from "../../../doc-generator/knowledge-doc-input";
import type { KnowledgeDocPrompt } from "../../../doc-generator/knowledge-doc-prompt";
import {
  formatGroundingRules,
  formatKnowledgeDocContext,
  formatMarkdownOutputRules,
} from "../shared/prompt-formatting";

export function buildArchitecturePrompt(
  input: KnowledgeDocGenerationInput,
): KnowledgeDocPrompt {
  return {
    system: [
      "You are a senior software architect working for Bridger, a tool that prepares repositories for AI coding agents.",
      "",
      "Your task is to generate `architecture.md`: a compact operating guide to how this repository is structured and how future coding agents should reason about where changes belong.",
      "",
      "The goal is not to describe every folder or prove every claim with citations. The goal is to extract useful architectural knowledge from the codebase: entry points, boundaries, layers, flows, central modules, and risky areas.",
      "",
      "This document should help an AI coding agent answer:",
      "1. Where should I look before changing a feature?",
      "2. Where does a new file or change likely belong?",
      "3. What are the main architectural boundaries?",
      "4. Which parts of the app appear central or risky?",
      "5. What assumptions about structure or data flow would be unsafe?",
      "",
      "Critical rules:",
      "- Use only the provided repository context, file index summary, and important file excerpts.",
      "- Do not invent architecture layers, workflows, data flow, commands, ownership boundaries, or risky areas.",
      "- Treat source code and selected file excerpts as stronger evidence than README/docs.",
      "- Treat names of files/folders as clues, not proof, unless supported by code content.",
      "- Synthesize architectural understanding; do not create an evidence log.",
      "- Mention file paths only when the path is directly useful for implementation or inspection.",
      "- Do not cite a file for every statement.",
      "- Do not summarize files or folders one by one.",
      "- Do not restate the full file tree.",
      "- Do not restate dependencies or scripts unless they imply an architectural convention.",
      "- Separate observed structure, cautious inferences, and unknowns.",
      "- Prefer practical repo navigation and change-placement guidance over generic architecture language.",
      "- Do not write implementation plans, refactoring suggestions, or tickets.",
      "- Do not mention these instructions or say that you are an AI.",
    ].join("\n"),
    prompt: [
      "# Task",
      "Generate `architecture.md` for this repository.",
      "",
      "Write this as a concise, human-readable operating guide for coding agents.",
      "",
      "Do not optimize for exhaustive Markdown structure. Optimize for useful extracted architectural knowledge.",
      "",
      "# Output shape",
      "Use these sections, but keep them compact and merge subpoints when useful:",
      "",
      "## Architectural overview",
      "Explain what kind of repository this appears to be and how the main pieces fit together. Only state a product or architectural purpose when the provided context supports it.",
      "",
      "If the purpose or architecture is unclear, say so directly.",
      "",
      "## Main entry points and execution paths",
      "Identify the practical entry points an agent should understand before changing behavior. This may include app routes, pages, API handlers, CLI commands, server actions, workers, scripts, config entry points, or runtime bootstrapping files.",
      "",
      "Explain what each entry point appears to control. Mention file paths only when they are useful places to inspect.",
      "",
      "## Major layers and boundaries",
      "Describe the main architectural layers visible in the repo. Focus on boundaries that affect implementation decisions.",
      "",
      "Useful boundaries may include:",
      "- app/routes/pages versus reusable components;",
      "- server-only code versus client-side code;",
      "- CLI layer versus core logic;",
      "- domain/business logic versus infrastructure helpers;",
      "- validation/schema boundaries;",
      "- data-access or persistence boundaries;",
      "- generated output versus source code;",
      "- tests/fixtures versus production code.",
      "",
      "If a boundary is weak or unclear, explain the practical risk for coding agents.",
      "",
      "## Where changes likely belong",
      "Give practical guidance for placing future changes based on the observed structure.",
      "",
      "Answer questions like:",
      "- Where would a UI/component change likely go?",
      "- Where would domain or business behavior likely go?",
      "- Where would validation or schema changes likely go?",
      "- Where would CLI command behavior likely go?",
      "- Where would tests or fixtures likely go?",
      "- Which folders should be inspected before touching central behavior?",
      "",
      "Do not invent folders that are not present. If placement is unclear, say what an agent should inspect first.",
      "",
      "## Data and control flow",
      "Describe visible flow through the application only where it is supported by the context. Focus on how data or control appears to move between entry points, core modules, validation, persistence, generated outputs, or external calls.",
      "",
      "If flow is only partially visible, describe the visible part and mark the rest as unknown.",
      "",
      "Do not infer a complete end-to-end flow from naming alone.",
      "",
      "## Commands and verification hooks",
      "Summarize available commands that matter for coding agents: install, dev, build, lint, typecheck, test, and format.",
      "",
      "Use commands exactly as provided by repo context. If a command category is missing, say it was not detected.",
      "",
      "Keep this section short. The purpose is to help agents verify changes, not to document package scripts exhaustively.",
      "",
      "## Central and risky areas",
      "Identify areas where agents should be cautious because they appear central, cross-cutting, generated, configuration-heavy, persistence-related, or connected to external side effects.",
      "",
      "For each risky area, explain:",
      "- why careless changes could be costly;",
      "- what kind of changes should be scoped carefully;",
      "- what an agent should inspect before editing.",
      "",
      "Mention paths only when they are actionable.",
      "",
      "## Architectural unknowns",
      "List gaps in architectural evidence that future coding agents should not assume.",
      "",
      "Good unknowns:",
      "- data flow is not fully visible from selected files;",
      "- persistence boundaries are unclear;",
      "- server/client ownership is only partially evidenced;",
      "- tests or verification flows are not visible;",
      "- generated files or framework-managed files may exist but are not clearly documented;",
      "- external side effects are suggested but not represented in selected context.",
      "",
      "Phrase unknowns as practical warnings for future implementation work.",
      "",
      "# Style rules",
      "- Write plain Markdown.",
      "- Be compact and practical.",
      "- Prefer short paragraphs and focused bullets.",
      "- Avoid decorative Markdown.",
      "- Avoid bold and italic unless essential.",
      "- Do not include an evidence trail.",
      "- Do not use `Observed:`, `Evidence:`, `Assumption:`, `Unknown:`, and `Confidence:` labels for every bullet.",
      "- Do not cite file paths after every claim.",
      "- Mention a path only when it helps the agent know where to inspect, place code, copy a pattern, or avoid a risky edit.",
      "- Avoid generic architecture filler.",
      "- Avoid long lists of folders with shallow descriptions.",
      "- Prefer fewer, stronger architectural insights.",
      "- Use cautious language when evidence is weak: `appears to`, `likely`, `unclear`, `not visible from the selected context`.",
      "- Do not include code blocks unless absolutely necessary.",
      "",
      "# Grounding rules",
      formatGroundingRules(),
      "",
      "# Output rules",
      formatMarkdownOutputRules(),
      "",
      "# Repo context",
      formatKnowledgeDocContext(input),
    ].join("\n"),
  };
}
