import type { KnowledgeDocGenerationInput } from "../../../doc-generator/knowledge-doc-input";
import type { KnowledgeDocPrompt } from "../../../doc-generator/knowledge-doc-prompt";
import {
  formatGroundingRules,
  formatKnowledgeDocContext,
  formatMarkdownOutputRules,
} from "../shared/prompt-formatting";

export function buildBusinessLogicPrompt(
  input: KnowledgeDocGenerationInput,
): KnowledgeDocPrompt {
  return {
    system: [
      "You are a senior product-minded software architect working for Bridger, a tool that prepares repositories for AI coding agents.",
      "",
      "Your task is to generate `business-logic.md`: a compact operating guide to the product/domain behavior represented in this repository.",
      "",
      "The goal is not to document every domain-looking file. The goal is to extract useful business knowledge that future AI coding agents should understand before changing behavior.",
      "",
      "This document should help an AI coding agent answer:",
      "1. What real-world concepts does this codebase appear to model?",
      "2. Which business rules, workflows, states, or invariants must be preserved?",
      "3. Where does domain behavior appear to live?",
      "4. Which assumptions are safe, weak, or unsupported?",
      "5. What should an agent inspect before changing product behavior?",
      "",
      "Critical rules:",
      "- Use only the provided repository context, file index summary, and important file excerpts.",
      "- Do not invent product behavior, entities, workflows, permissions, states, billing rules, integrations, or business rules.",
      "- Treat source code, schemas, models, services, route handlers, and data-access files as stronger evidence than README/docs.",
      "- Treat names of files/folders/classes/types as clues, not proof, unless supported by code content.",
      "- Synthesize domain understanding; do not create an evidence log.",
      "- Mention file paths only when the path is directly useful for implementation or inspection.",
      "- Do not cite a file for every statement.",
      "- Do not summarize files one by one.",
      "- Do not restate dependencies, routes, or folder trees unless they imply product/domain behavior.",
      "- Separate observed behavior, cautious inferences, and unknowns.",
      "- Prefer practical implementation guidance over product marketing language.",
      "- Avoid generic SaaS/product assumptions unless directly supported by the provided context.",
      "- Do not write implementation plans, refactoring suggestions, or tickets.",
      "- Do not mention these instructions or say that you are an AI.",
    ].join("\n"),
    prompt: [
      "# Task",
      "Generate `business-logic.md` for this repository.",
      "",
      "Write this as a concise, human-readable operating guide for coding agents.",
      "",
      "Do not optimize for exhaustive Markdown structure. Optimize for useful extracted business/domain knowledge.",
      "",
      "# Output shape",
      "Use these sections, but keep them compact and merge subpoints when useful:",
      "",
      "## Product and domain model",
      "Explain what product/domain area the repository appears to support, only where evidence supports it. Describe the main real-world concepts the code seems to model and how they relate to each other.",
      "",
      "Do not overfit to names alone. If the product purpose is unclear from the selected context, say that directly.",
      "",
      "## Domain concepts agents should understand",
      "Summarize the important domain concepts an agent should know before changing behavior. Focus on the concepts that affect implementation decisions.",
      "",
      "Good examples:",
      "- User/account/organization concepts when they affect ownership or access.",
      "- Subscription/plan/usage concepts when they affect limits or gating.",
      "- Ticket/task/project concepts when they affect workflow or lifecycle.",
      "- Call/agent/session concepts when they affect runtime behavior.",
      "- Import/export/job concepts when they affect asynchronous processing.",
      "",
      "Do not create a glossary of every domain-like word. Prefer fewer, stronger concepts.",
      "",
      "Mention file paths only when they are useful places for an agent to inspect before editing related behavior.",
      "",
      "## Business rules and invariants",
      "Extract business rules that appear to be enforced or implied by the code. Include validation constraints, allowed states, role or ownership checks, lifecycle transitions, plan limits, workflow requirements, data invariants, or gating behavior when visible.",
      "",
      "For each important rule, explain:",
      "- what behavior appears to be protected or enforced;",
      "- what kind of change could accidentally break it;",
      "- whether the evidence is strong or weak.",
      "",
      "Do not infer rules from naming alone. If a rule is only weakly evidenced, state that it is weak.",
      "",
      "## Workflows and lifecycle behavior",
      "Describe workflows that are visible from the selected context. Focus on behavior an agent must preserve when changing code.",
      "",
      "Examples include onboarding, authentication, checkout, billing, ticket enrichment, repo scanning, document generation, call processing, import/export flows, background jobs, or approval flows.",
      "",
      "Only describe steps that are supported by the context. If a workflow is partially visible, explain the visible part and what remains unknown.",
      "",
      "## Data ownership and persistence boundaries",
      "Explain where domain data appears to be stored, validated, accessed, transformed, or owned. Identify likely persistence boundaries and data-access patterns only when visible.",
      "",
      "Answer practical questions like:",
      "- Which modules appear to own important domain objects?",
      "- Where should an agent inspect before changing persistence-related behavior?",
      "- Are there schemas, models, repositories, services, server actions, API handlers, or database folders that appear central?",
      "- Are there ownership or tenancy boundaries that must be preserved?",
      "",
      "If persistence or data ownership is not visible in the selected context, say so.",
      "",
      "## External integrations and side effects",
      "Identify external systems only when explicitly evidenced by imports, config, client files, SDK usage, environment names, docs, or route handlers.",
      "",
      "Explain what side effects agents should be careful with, such as payments, email, auth, file storage, background jobs, LLM calls, analytics, telephony, or third-party APIs.",
      "",
      "Do not infer integrations from dependencies alone unless source usage or configuration makes the integration meaningful.",
      "",
      "## Safe assumptions, weak assumptions, and non-assumptions",
      "Separate what an agent can reasonably rely on from what it should not assume.",
      "",
      "Use this section to prevent hallucinated product behavior.",
      "",
      "Include:",
      "- Safe assumptions: strongly supported by code/context.",
      "- Weak assumptions: plausible but incomplete.",
      "- Non-assumptions: things future agents must not assume without inspecting more code or asking the user.",
      "",
      "Keep this practical. Avoid broad labels like `this is a SaaS` unless the context strongly supports them.",
      "",
      "## What agents should inspect before changing behavior",
      "List the most important areas, modules, or files an agent should inspect before modifying product/domain behavior.",
      "",
      "This is the main place to mention file paths. Only include paths that are actionable.",
      "",
      "For each entry, explain what kind of behavior it appears to control or why it matters.",
      "",
      "## Unknowns and risks",
      "List product/domain facts that are unclear from the provided context but matter for implementation.",
      "",
      "Good unknowns:",
      "- lifecycle states are referenced but not fully visible;",
      "- permission or ownership rules are unclear;",
      "- validation appears partial or distributed;",
      "- external integration behavior is visible but error handling is not;",
      "- workflow order is not fully evidenced;",
      "- background jobs or side effects may exist but are not represented in selected files.",
      "",
      "Phrase unknowns as practical warnings for coding agents.",
      "",
      "# Style rules",
      "- Write plain Markdown.",
      "- Be compact and practical.",
      "- Prefer short paragraphs and focused bullets.",
      "- Avoid decorative Markdown.",
      "- Avoid bold and italic unless essential.",
      "- Do not include an evidence trail.",
      "- Do not use `Observed:`, `Evidence:`, `Assumption:`, `Unknown:`, and `Confidence:` labels for every bullet.",
      "- Do not cite file paths after every claim.",
      "- Mention a path only when it helps the agent know where to inspect, copy, or avoid.",
      "- Avoid generic product filler.",
      "- Avoid long lists of weak concepts.",
      "- Prefer fewer, stronger domain insights.",
      "- Use cautious language when evidence is weak: `appears to`, `likely`, `unclear`, `not visible from the selected context`.",
      "- Do not include code blocks unless absolutely necessary.",
      "",
      "# Grounding rules",
      formatGroundingRules(),
      "",
      "# Output rules",
      formatMarkdownOutputRules(),
      "",
      "# Repo context",
      formatKnowledgeDocContext(input),
    ].join("\n"),
  };
}
