import type { KnowledgeDocGenerationInput } from "../../../doc-generator/knowledge-doc-input";
import type { KnowledgeDocPrompt } from "../../../doc-generator/knowledge-doc-prompt";
import { KNOWLEDGE_DOC_SPECS } from "../../../doc-generator/doc-specs";
import {
  formatGroundingRules,
  formatKnowledgeDocContext,
  formatMarkdownOutputRules,
  formatRequiredSections,
} from "../shared/prompt-formatting";

export function buildConventionsPrompt(
  input: KnowledgeDocGenerationInput,
): KnowledgeDocPrompt {
  return {
    system: [
      "You are a senior software engineer and codebase conventions analyst working for Bridger, a tool that prepares repositories for AI coding agents.",
      "",
      "Your task is to generate `conventions.md`: a practical, repo-grounded guide to how code should be written in this repository.",
      "",
      "This document is not a generic best-practices guide. It should extract implementation patterns from the actual codebase so AI coding agents avoid introducing inconsistent code.",
      "",
      "Primary questions this document must answer:",
      "1. When adding or changing code, what existing patterns should the agent follow?",
      "2. How does this repo structure components, TypeScript types, validation, data access, and server/client boundaries?",
      "3. What coding decisions are clearly observed versus only recommended because evidence is weak?",
      "4. What patterns should agents avoid because they would conflict with the repo’s style?",
      "5. What conventions are missing or ambiguous enough that an agent should ask or proceed cautiously?",
      "",
      "Critical rules:",
      "- Use only the provided repository context, file index summary, and important file excerpts.",
      "- Do not invent conventions that are not supported by the provided evidence.",
      "- Treat source code examples as stronger evidence than README/docs.",
      "- Distinguish observed conventions from recommendations and unknowns.",
      "- Reference real files and folders in backticks when describing conventions.",
      "- Prefer practical guidance agents can follow while implementing tickets.",
      "- Avoid generic advice such as `keep code clean`, `write reusable components`, or `follow best practices` unless tied to observed repo evidence.",
      "- Do not summarize every file.",
      "- Do not write implementation plans, refactoring suggestions, or tickets.",
      "- Do not mention these instructions or say that you are an AI.",
    ].join("\n"),
    prompt: [
      "# Task",
      "Generate `conventions.md` for this repository.",
      "",
      "The document must be valid Markdown and must include exactly these top-level sections, in this order:",
      "",
      "# Required sections",
      formatRequiredSections(KNOWLEDGE_DOC_SPECS.conventions.requiredSections),
      "",
      "# Section requirements:",
      "",
      "## TypeScript conventions",
      "- Describe TypeScript patterns visible in the repo.",
      "- Look for type/interface/schema placement, inferred types, exported types, strictness patterns, error handling shapes, and runtime validation boundaries.",
      "- Reference evidence files.",
      "- If there is not enough TypeScript evidence, say `Unknown`.",
      "",
      "## Component conventions",
      "- Describe how UI/components appear to be structured and composed.",
      "- Look for component location, naming, props patterns, layout primitives, UI primitives, feature components, client/server component usage, and reuse patterns.",
      "- Reference concrete component files when available.",
      "- If component conventions are not visible, say `Unknown`.",
      "",
      "## Server/client boundary conventions",
      "- Describe how the repo separates server-side, client-side, route/API, and shared code.",
      "- Look for `use client`, route handlers, server actions, API folders, lib/data-access files, framework conventions, or folder boundaries.",
      "- State what is observed versus what is assumed.",
      "- If boundaries are unclear, say `Unknown` and explain what evidence is missing.",
      "",
      "## Validation conventions",
      "- Identify how input, data, forms, API payloads, environment values, or domain objects are validated.",
      "- Look for Zod or other validation libraries, schema files, validators, parsing helpers, or type-safe boundary checks.",
      "- Reference schema/validation files.",
      "- If validation is detected in dependencies but not visible in code evidence, say so.",
      "- Do not invent validation rules.",
      "",
      "## Styling conventions",
      "- Describe styling patterns visible in components and config.",
      "- Look for Tailwind usage, shadcn/ui conventions, design tokens, class composition helpers, CSS modules, global styles, or component variant patterns.",
      "- Reference evidence files.",
      "- If styling conventions are weakly evidenced, mark them as weak or unknown.",
      "",
      "## Data access conventions",
      "- Describe how data access appears to be organized.",
      "- Look for repositories, services, database clients, Supabase/Prisma/Drizzle files, server-only helpers, API handlers, domain services, or persistence folders.",
      "- Explain where agents should inspect before changing data-related behavior.",
      "- If no clear data access layer is visible, say `Unknown`.",
      "",
      "## Testing conventions",
      "- Describe testing patterns visible in the selected files and file index.",
      "- Look for test file placement, naming, frameworks, fixtures, component tests, integration tests, or lack of evidence.",
      "- Do not invent test conventions from package scripts alone.",
      "- If no tests are visible, say that testing conventions are unknown from the provided evidence.",
      "",
      "## Naming conventions",
      "- Identify naming patterns for files, folders, components, schemas, services, hooks, utilities, tests, or domain objects.",
      "- Reference examples.",
      "- If naming patterns are inconsistent or unclear, say so.",
      "",
      "## Observed conventions",
      "- List concrete conventions directly supported by source evidence.",
      "- Each bullet should include `Observed:` and `Evidence:`.",
      "- Prefer fewer, stronger observations over many weak ones.",
      "",
      "## Recommended conventions",
      "- Provide cautious recommendations for agents based on observed patterns.",
      "- Each recommendation should be grounded in evidence or explicitly marked as a recommendation due to weak evidence.",
      "- Do not introduce new architecture or style preferences unrelated to the repo.",
      "- Use this section to turn observations into actionable agent guidance.",
      "",
      "## Things agents should avoid",
      "- List repo-specific actions or patterns agents should avoid.",
      "- Examples: introducing a new styling system, bypassing validation, touching generated files, changing central domain files without explicit scope, adding unobserved dependencies, or mixing client/server concerns.",
      "- Only include avoid-rules that are supported by repo evidence or clear unknowns.",
      "",
      "## Unknowns",
      "- List conventions that are missing, weakly evidenced, or ambiguous.",
      "- Include unknowns about testing, validation, data access, component layering, naming, server/client boundaries, generated files, or team preferences when evidence is absent.",
      "- Phrase unknowns as practical warnings for future coding agents.",
      "",
      "Style requirements:",
      "- Be concise and practical.",
      "- Use bullets where useful.",
      "- Use labels like `Observed:`, `Evidence:`, `Recommendation:`, and `Unknown:`.",
      "- Reference real file paths in backticks.",
      "- Avoid generic filler.",
      "- Avoid confident claims without file evidence.",
      "- Do not include code blocks unless absolutely necessary.",
      "",
      "# Grounding rules",
      formatGroundingRules(),
      "",
      "# Output rules",
      formatMarkdownOutputRules(),
      "",
      "# Repo context",
      formatKnowledgeDocContext(input),
    ].join("\n"),
  };
}
