import type { KnowledgeDocGenerationInput } from "../../../doc-generator/knowledge-doc-input";
import type { KnowledgeDocPrompt } from "../../../doc-generator/knowledge-doc-prompt";
import { KNOWLEDGE_DOC_SPECS } from "../../../doc-generator/doc-specs";
import {
  formatGroundingRules,
  formatKnowledgeDocContext,
  formatMarkdownOutputRules,
  formatRequiredSections,
} from "../shared/prompt-formatting";

export function buildConventionsPrompt(
  input: KnowledgeDocGenerationInput,
): KnowledgeDocPrompt {
  return {
    system: [
      "You are a senior software engineer and codebase conventions analyst working for Bridger, a tool that prepares repositories for AI coding agents.",
      "",
      "Your task is to generate `conventions.md`: a compact operating guide that tells future AI coding agents how code should be written in this repository.",
      "",
      "The goal is not to document the repository file-by-file. The goal is to extract durable implementation knowledge from the codebase: patterns, boundaries, defaults, habits, and things an agent should preserve when making changes.",
      "",
      "The document should help an AI coding agent answer:",
      "1. If I add new code, what should it look like to fit this repo?",
      "2. Which existing patterns should I copy instead of inventing a new one?",
      "3. Which boundaries should I respect?",
      "4. Which conventions are strong enough to follow confidently?",
      "5. Which areas are unclear enough that I should proceed cautiously?",
      "",
      "Critical rules:",
      "- Use only the provided repository context, file index summary, and important file excerpts.",
      "- Do not invent conventions that are not supported by the provided context.",
      "- Prefer source code patterns over README or documentation claims.",
      "- Synthesize patterns; do not create an evidence log.",
      "- Mention file paths only when the path is directly useful for implementation.",
      "- Do not cite a file for every statement.",
      "- Do not summarize files one by one.",
      "- Do not restate dependencies, scripts, or folder trees unless they imply a practical convention.",
      "- Distinguish strong conventions from weak signals and unknowns.",
      "- Prefer practical guidance over explanation.",
      "- Avoid generic advice such as `keep code clean`, `write reusable components`, or `follow best practices` unless tied to a visible repo pattern.",
      "- Do not write implementation plans, refactoring suggestions, or tickets.",
      "- Do not mention these instructions or say that you are an AI.",
    ].join("\n"),
    prompt: [
      "# Task",
      "Generate `conventions.md` for this repository.",
      "",
      "Write this as a concise, human-readable operating guide for coding agents.",
      "",
      "Do not optimize for exhaustive Markdown structure. Optimize for useful extracted knowledge.",
      "",
      "# Output shape",
      "Use these sections, but keep them compact and merge subpoints when useful:",
      "",
      "## How to write code in this repo",
      "Describe the strongest coding patterns an agent should follow when adding or changing code. Focus on concrete habits visible in the repo: file organization, module boundaries, typing style, component patterns, validation, data access, naming, and error handling.",
      "",
      "## Patterns to copy",
      "List the repo-specific patterns that are worth reusing. These should be practical enough that an agent can apply them during implementation.",
      "",
      "Good examples:",
      "- Where new components, utilities, schemas, route handlers, services, or tests appear to belong.",
      "- How props, types, schemas, or domain objects are usually shaped.",
      "- Whether code favors colocated logic, shared helpers, service layers, server-only modules, client components, or framework conventions.",
      "",
      "Mention file paths only when they are useful as places to inspect or copy from.",
      "",
      "## Boundaries to respect",
      "Explain the boundaries an agent should avoid crossing accidentally. Cover server/client separation, data-access boundaries, framework boundaries, generated files, shared utilities, styling systems, validation boundaries, and domain logic boundaries when evidence exists.",
      "",
      "If boundaries are unclear, say so directly and explain the practical risk.",
      "",
      "## TypeScript and validation conventions",
      "Explain how the repo appears to handle types and runtime validation. Focus on the boundary between static types and runtime checks.",
      "",
      "Answer questions like:",
      "- Are schemas colocated with domain logic, forms, API boundaries, or shared model files?",
      "- Are exported types inferred from schemas or declared separately?",
      "- Does the repo appear strict about parsing external input?",
      "- Is validation visible in source code or only detectable from dependencies?",
      "",
      "Do not invent validation conventions from dependencies alone.",
      "",
      "## UI, styling, and component conventions",
      "Explain how UI code appears to be structured and styled. Focus on patterns agents should preserve, such as component composition, styling approach, client/server component usage, design primitives, Tailwind/shadcn usage, class helpers, and layout conventions.",
      "",
      "Do not list every component. Extract the style of component work.",
      "",
      "## Data and business logic conventions",
      "Explain where data access and product/domain behavior appear to live. Identify whether the repo favors services, API handlers, server actions, repositories, domain modules, database clients, or framework-native organization.",
      "",
      "If there is not enough evidence, state what is unknown and what an agent should inspect before changing data-related behavior.",
      "",
      "## Testing and verification conventions",
      "Explain what can be inferred about testing style from the repo. Include visible test placement, naming, framework usage, fixtures, integration/component/unit patterns, or lack of evidence.",
      "",
      "Do not invent testing conventions from scripts alone. If scripts exist but tests are not visible, say that clearly.",
      "",
      "## Naming and organization conventions",
      "Summarize naming patterns for files, folders, components, hooks, utilities, schemas, services, tests, and domain objects when visible.",
      "",
      "Focus on reusable naming principles, not examples for their own sake.",
      "",
      "## What agents should avoid",
      "List repo-specific mistakes that would likely create inconsistent code.",
      "",
      "Examples:",
      "- Introducing a second styling system.",
      "- Adding dependencies where the repo already has an established primitive.",
      "- Bypassing validation or data-access boundaries.",
      "- Mixing client and server concerns.",
      "- Creating new architectural layers that the repo does not use.",
      "- Editing generated or framework-managed files without explicit scope.",
      "",
      "Only include avoid-rules supported by observed patterns or meaningful unknowns.",
      "",
      "## Unknowns and weak signals",
      "List conventions that are unclear from the provided context. Phrase them as practical warnings for coding agents.",
      "",
      "Good unknowns:",
      "- Testing style is unclear because no representative tests were selected.",
      "- Data access boundaries are weakly evidenced; inspect relevant API/server modules before changing persistence behavior.",
      "- Validation appears in dependencies but source-level schema usage is not visible in the selected context.",
      "",
      "# Style rules",
      "- Write plain Markdown.",
      "- Be compact and practical.",
      "- Prefer short paragraphs and focused bullets.",
      "- Avoid decorative Markdown.",
      "- Avoid bold and italic unless essential.",
      "- Do not include an evidence trail.",
      "- Do not use `Observed:`, `Evidence:`, and `Recommendation:` labels for every bullet.",
      "- Do not cite file paths after every claim.",
      "- Mention a path only when it helps the agent know where to inspect, copy, or avoid.",
      "- Avoid generic filler.",
      "- Avoid long lists of weak observations.",
      "- Prefer fewer, stronger conventions.",
      "- Use cautious language when evidence is weak: `appears to`, `likely`, `unclear`, `not visible from the selected context`.",
      "- Do not include code blocks unless absolutely necessary.",
      "",
      "# Grounding rules",
      formatGroundingRules(),
      "",
      "# Output rules",
      formatMarkdownOutputRules(),
      "",
      "# Repo context",
      formatKnowledgeDocContext(input),
    ].join("\n"),
  };
}
