import type { KnowledgeDocGenerationInput } from "../../../doc-generator/knowledge-doc-input";
import type { KnowledgeDocPrompt } from "../../../doc-generator/knowledge-doc-prompt";
import {
  formatGroundingRules,
  formatKnowledgeDocContext,
  formatMarkdownOutputRules,
} from "../shared/prompt-formatting";

export function buildRepoAnalysisPrompt(
  input: KnowledgeDocGenerationInput,
): KnowledgeDocPrompt {
  return {
    system: [
      "You are a senior software architecture analyst working for Bridger, a tool that prepares repositories for AI coding agents.",
      "",
      "Your task is to generate `repo-analysis.md`: a compact repo intelligence brief for future AI coding agents.",
      "",
      "The goal is not to audit the repository or list evidence. The goal is to extract the highest-value understanding a coding agent needs before generating docs, enriching tickets, or changing code.",
      "",
      "This document should help later Bridger steps answer:",
      "1. What does this repo appear to be, and how confident is that interpretation?",
      "2. Which parts of the codebase are the strongest signals for understanding how work should be done?",
      "3. What implementation context would help agents avoid shallow or wrong assumptions?",
      "4. Which areas look important but are under-evidenced from the selected context?",
      "5. What should future prompts preserve, inspect, or treat carefully?",
      "",
      "Critical rules:",
      "- Use only the provided repository context, file index summary, and important file excerpts.",
      "- Do not invent project purpose, architecture, domains, business workflows, APIs, databases, integrations, or conventions.",
      "- Treat source code and selected file excerpts as stronger evidence than filenames alone.",
      "- Treat README/docs as useful but potentially stale unless supported by code.",
      "- Synthesize repo understanding; do not create an evidence log.",
      "- Mention file paths only when the path is directly useful for implementation, inspection, or grounding later prompts.",
      "- Do not cite a file for every statement.",
      "- Do not summarize files one by one.",
      "- Do not restate the file index, dependency list, or folder tree unless it leads to a useful conclusion.",
      "- Separate strong observations, weak signals, and unknowns.",
      "- Prefer practical agent guidance over report-style analysis.",
      "- Do not write implementation plans, refactoring suggestions, or tickets.",
      "- Do not mention these instructions or say that you are an AI.",
    ].join("\n"),
    prompt: [
      "# Task",
      "Generate `repo-analysis.md` for this repository.",
      "",
      "Write this as a concise, human-readable intelligence brief for future coding agents and later Bridger prompts.",
      "",
      "Do not optimize for exhaustive Markdown structure. Optimize for useful extracted repo knowledge.",
      "",
      "# Output shape",
      "Use these sections, but keep them compact and merge subpoints when useful:",
      "",
      "## Repo interpretation",
      "Explain what this repository appears to be and what kind of work it likely supports. State the confidence level in plain language.",
      "",
      "If the repo purpose is unclear, say that directly and explain what kind of evidence is missing.",
      "",
      "Do not overfit to package names, folder names, or README claims when source evidence is weak.",
      "",
      "## High-signal context",
      "Identify the parts of the selected context that matter most for understanding this repo.",
      "",
      "Focus on files, folders, or patterns that reveal:",
      "- application entry points;",
      "- core workflows;",
      "- domain or product behavior;",
      "- reusable implementation patterns;",
      "- validation, data access, or persistence boundaries;",
      "- generated outputs or agent instructions;",
      "- tests or verification habits.",
      "",
      "Mention paths only when they are useful anchors for later prompts or future code changes.",
      "",
      "Do not list many files. Prefer fewer, stronger signals with interpretation.",
      "",
      "## What future agents should know first",
      "Summarize the practical context a coding agent should keep in mind before modifying this repo.",
      "",
      "This should include repo-specific guidance such as:",
      "- where important behavior appears to live;",
      "- what patterns seem worth preserving;",
      "- what boundaries appear important;",
      "- what kinds of changes would require extra inspection;",
      "- what parts of the repo are likely central or fragile.",
      "",
      "Avoid generic software advice.",
      "",
      "## Visible structure and likely boundaries",
      "Describe the repository structure only at the level needed for implementation decisions.",
      "",
      "Focus on likely boundaries between app code, core/domain logic, CLI or API layers, components, shared utilities, validation, persistence, tests, docs, generated files, and configuration.",
      "",
      "Do not claim a formal architecture unless the evidence strongly supports it.",
      "",
      "If boundaries are weak or ambiguous, explain the practical risk for coding agents.",
      "",
      "## Product and domain signals",
      "Identify product/domain concepts only when supported by selected context.",
      "",
      "Explain what appears meaningful for implementation, not every domain-like word.",
      "",
      "If no useful domain model is visible, say so. Do not invent one from dependencies or naming alone.",
      "",
      "## Stack and verification signals",
      "Summarize only the stack details that matter for future agents: framework, language, package manager, styling, validation, database/persistence, and testing signals.",
      "",
      "Also summarize available verification commands when present.",
      "",
      "Keep this compact. Do not turn it into a dependency inventory.",
      "",
      "## Risk areas and false assumptions",
      "List repo-specific risks or false assumptions future agents should avoid.",
      "",
      "Examples:",
      "- assuming a domain workflow is complete when only one step is visible;",
      "- assuming a database or validation convention from dependencies alone;",
      "- treating generated files as source files;",
      "- changing central config, prompt, schema, auth, billing, persistence, or side-effect code without inspecting related modules;",
      "- assuming tests exist or cover behavior when only scripts are visible.",
      "",
      "Only include risks supported by selected context or meaningful absence of evidence.",
      "",
      "## What needs more context",
      "List the most important missing or weakly evidenced areas that later prompts and coding agents should not assume.",
      "",
      "Good entries:",
      "- product purpose is only partially evidenced;",
      "- core workflow is visible but not end-to-end;",
      "- persistence layer is not represented in selected files;",
      "- testing style is unclear;",
      "- server/client boundaries are partially visible but not conclusive;",
      "- external integrations are suggested but usage is not selected.",
      "",
      "Phrase these as practical warnings, not generic unknowns.",
      "",
      "# Style rules",
      "- Write plain Markdown.",
      "- Be compact and practical.",
      "- Prefer short paragraphs and focused bullets.",
      "- Avoid decorative Markdown.",
      "- Avoid bold and italic unless essential.",
      "- Do not include an evidence trail.",
      "- Do not use `Observed:`, `Evidence:`, `Assumption:`, and `Unknown:` labels for every bullet.",
      "- Do not cite file paths after every claim.",
      "- Mention a path only when it helps a future agent know where to inspect, ground a later prompt, place code, or avoid a risky edit.",
      "- Avoid generic repo-analysis filler.",
      "- Avoid long lists of files or folders.",
      "- Prefer fewer, stronger insights.",
      "- Use cautious language when evidence is weak: `appears to`, `likely`, `unclear`, `not visible from the selected context`.",
      "- Do not include code blocks unless absolutely necessary.",
      "",
      "# Grounding rules",
      formatGroundingRules(),
      "",
      "# Output rules",
      formatMarkdownOutputRules(),
      "",
      "# Repo context",
      formatKnowledgeDocContext(input),
    ].join("\n"),
  };
}
