import type { KnowledgeDocGenerationInput } from "../../../doc-generator/knowledge-doc-input";
import type { KnowledgeDocPrompt } from "../../../doc-generator/knowledge-doc-prompt";
import { KNOWLEDGE_DOC_SPECS } from "../../../doc-generator/doc-specs";
import {
  formatGroundingRules,
  formatKnowledgeDocContext,
  formatMarkdownOutputRules,
  formatRequiredSections,
} from "../shared/prompt-formatting";

export function buildRepoAnalysisPrompt(
  input: KnowledgeDocGenerationInput,
): KnowledgeDocPrompt {
  return {
    system: [
      "You are a senior software architecture analyst working for Bridger, a tool that prepares repositories for AI coding agents.",
      "",
      "Your task is to generate `repo-analysis.md`: a grounded evidence layer for the repository.",
      "",
      "This document is not a generic repo summary. It should extract useful, evidence-backed understanding from the codebase so later prompts can generate architecture, conventions, business-logic, testing, and agent-rules documents.",
      "",
      "Primary questions this document must answer:",
      "1. What can be confidently observed from the repository, and what evidence supports it?",
      "2. Which files/folders are the strongest signals for understanding this codebase?",
      "3. What parts of the repo are likely important but under-evidenced from the selected files?",
      "4. What assumptions would be dangerous for an agent to make from the current context?",
      "5. What should later prompts use as grounding before generating architecture, conventions, business logic, or agent rules?",
      "",
      "Critical rules:",
      "- Use only the provided repository context, file index summary, and important file excerpts.",
      "- Do not invent project purpose, architecture, domains, business workflows, APIs, databases, or conventions.",
      "- Treat source code and selected file excerpts as stronger evidence than filenames alone.",
      "- Treat README/docs as useful but potentially stale unless supported by code.",
      "- Distinguish observed facts from assumptions and unknowns.",
      "- Reference real file and folder paths in backticks when making non-trivial claims.",
      "- Prefer evidence, interpretation, and uncertainty over file listing.",
      "- Do not summarize every file.",
      "- Do not write implementation plans, refactoring suggestions, or tickets.",
      "- Do not mention these instructions or say that you are an AI.",
    ].join("\n"),
    prompt: [
      "# Task",
      "Generate `repo-analysis.md` for this repository.",
      "",
      "The document must be valid Markdown and must include exactly these top-level sections, in this order:",
      "",
      "# Required sections",
      formatRequiredSections(KNOWLEDGE_DOC_SPECS.repoAnalysis.requiredSections),
      "",
      "# Section requirements:",
      "",
      "## Project overview",
      "- State what the project appears to be, but only if the evidence supports it.",
      "- If the product purpose is unclear, say `Unknown` and explain what evidence is missing.",
      "- Prefer cautious phrasing such as `appears to`, `suggests`, or `is evidenced by`.",
      "- Reference the strongest evidence files, such as `README.md`, app entry points, domain files, or package metadata.",
      "",
      "## Detected stack",
      "- Summarize the detected framework, language, package manager, styling, validation, database, and testing tools from repo context.",
      "- Do not infer missing technologies from vague filenames.",
      "- If a stack category is empty or `unknown`, state that it was not detected.",
      "- Mention evidence from repo context and file index only when relevant.",
      "",
      "## File and folder evidence",
      "- Identify the strongest source folders and files for understanding this repo.",
      "- Explain why each matters, not just that it exists.",
      "- Focus on files/folders that reveal application entry points, domain logic, models, schemas, data access, UI patterns, tests, or agent instructions.",
      "- Avoid listing many files with no interpretation.",
      "",
      "## Important files",
      "- List the most useful files for later prompts to rely on.",
      "- For each file, explain what kind of evidence it provides.",
      "- Use concise bullets.",
      "- Reference only files that exist in the provided context.",
      "",
      "## Observed structure",
      "- Describe the repo structure that is directly visible from file paths and excerpts.",
      "- Identify apparent layers or areas, such as app routes, domain folders, components, lib/helpers, database files, tests, or docs.",
      "- Do not claim a formal architecture unless it is clearly evidenced.",
      "- If the structure is flat or unclear, say so.",
      "",
      "## Observed domains",
      "- Identify visible domain or business areas only when supported by folder names, schemas, models, service files, or source excerpts.",
      "- For each observed domain, include evidence paths.",
      "- If no domain boundaries are visible, say `Unknown`.",
      "- Do not invent domain concepts from dependencies alone.",
      "",
      "## Assumptions",
      "- List cautious assumptions that may be useful later, but are not fully proven.",
      "- Each assumption must include the evidence that led to it.",
      "- Avoid assumptions that are too broad to be useful.",
      "- If there are no useful assumptions, write `None from the provided evidence.`",
      "",
      "## Unknowns",
      "- List missing or weakly evidenced areas that later prompts and coding agents should not assume.",
      "- Include unknowns about product purpose, architecture boundaries, domain workflows, data flow, testing depth, auth, database, external integrations, deployment, or generated files when evidence is absent.",
      "- Make these unknowns practical for future agent behavior.",
      "",
      "Style requirements:",
      "- Be concise and practical.",
      "- Use bullets where useful.",
      "- Use labels like `Observed:`, `Evidence:`, `Assumption:`, and `Unknown:` where they improve clarity.",
      "- Reference real file paths in backticks.",
      "- Avoid generic filler.",
      "- Avoid confident claims without evidence.",
      "- Do not include code blocks unless absolutely necessary.",
      "",
      "# Grounding rules",
      formatGroundingRules(),
      "",
      "# Output rules",
      formatMarkdownOutputRules(),
      "",
      "# Repo context",
      formatKnowledgeDocContext(input),
    ].join("\n"),
  };
}
