import type { KnowledgeDocGenerationInput } from "../../../doc-generator/knowledge-doc-input";
import type { KnowledgeDocPrompt } from "../../../doc-generator/knowledge-doc-prompt";
import { KNOWLEDGE_DOC_SPECS } from "../../../doc-generator/doc-specs";
import {
  formatGroundingRules,
  formatKnowledgeDocContext,
  formatMarkdownOutputRules,
  formatRequiredSections,
} from "../shared/prompt-formatting";

export function buildTestingPrompt(
  input: KnowledgeDocGenerationInput,
): KnowledgeDocPrompt {
  return {
    system: [
      "You are a senior software engineer and testing strategy analyst working for Bridger, a tool that prepares repositories for AI coding agents.",
      "",
      "Your task is to generate `testing.md`: a practical, repo-grounded testing and verification guide for AI coding agents.",
      "",
      "This document is not a generic list of test commands. It should help agents decide what should be tested when implementing changes in this specific repository.",
      "",
      "Primary questions this document must answer:",
      "1. When implementing something new in this repo, what should be tested?",
      "2. When should an agent add unit tests, integration tests, regression tests, component/UI tests, or manual QA checks?",
      "3. What testing conventions are visible in this repo or team style?",
      "4. How should an agent verify changes without inventing unavailable commands or frameworks?",
      "5. What testing gaps or unknowns should make an agent cautious?",
      "",
      "Critical rules:",
      "- Use only the provided repository context, file index summary, and important file excerpts.",
      "- Do not invent test commands, frameworks, test folders, CI behavior, or QA processes.",
      "- Treat actual test files and source code evidence as stronger evidence than package scripts alone.",
      "- Package scripts and detected frameworks are useful, but they do not prove testing conventions by themselves.",
      "- Distinguish observed testing conventions from recommendations and unknowns.",
      "- Reference real files and folders in backticks when describing testing patterns.",
      "- Prefer practical guidance agents can use while implementing tickets.",
      "- Avoid generic testing advice unless it is tied to observed repo evidence.",
      "- Do not summarize every test file.",
      "- Do not write implementation plans, refactoring suggestions, or tickets.",
      "- Do not mention these instructions or say that you are an AI.",
    ].join("\n"),
    prompt: [
      "# Task",
      "Generate a grounded testing document for this repository.",
      "",
      "The document should help agents understand what should be tested when implementing new work, what test types are expected, and what testing conventions are visible in this repository.",
      "",
      "# Required sections",
      formatRequiredSections(KNOWLEDGE_DOC_SPECS.testing.requiredSections),
      "",
      "# Section requirements:",
      "",
      "## Testing philosophy",
      "- Explain the testing approach an agent should infer from the repo evidence.",
      "- If the repo has strong test evidence, summarize the apparent philosophy.",
      "- If the repo has weak or no test evidence, say so clearly and provide cautious verification guidance.",
      "- Do not invent team preferences.",
      "",
      "## Test types and when to use them",
      "- Explain when agents should add or update different kinds of tests for this repo.",
      "- Cover unit tests, integration tests, regression tests, component/UI tests, and manual QA checks when relevant.",
      "- Ground the guidance in observed repo structure, detected frameworks, source files, and existing tests.",
      "- If a test type is not evidenced, mark it as a recommendation or unknown, not an observed convention.",
      "",
      "## Unit testing conventions",
      "- Describe when unit tests are appropriate in this repo.",
      "- Look for utilities, domain services, schemas, validation logic, pure functions, or business rules that can be tested in isolation.",
      "- Reference existing unit test files or likely source files when available.",
      "- If no unit test convention is visible, say `Unknown` and explain what evidence is missing.",
      "",
      "## Integration testing conventions",
      "- Describe when integration tests are appropriate in this repo.",
      "- Look for API routes, server actions, data access boundaries, persistence layers, external clients, domain workflows, or multi-file flows.",
      "- Reference evidence files.",
      "- If integration test conventions are not visible, say `Unknown`.",
      "",
      "## Regression testing conventions",
      "- Explain when an agent should add regression coverage.",
      "- Focus on bug fixes, risky domain behavior, data access changes, validation changes, routing changes, and behavior that could silently break.",
      "- If the repo has existing regression-style tests, reference them.",
      "- If not, provide cautious guidance framed as a recommendation, not an observed convention.",
      "",
      "## Component and UI testing conventions",
      "- Describe when component or UI tests are appropriate.",
      "- Look for component folders, UI primitives, app routes, page components, client components, or existing component tests.",
      "- Reference concrete component or test files when available.",
      "- If the repo has UI code but no visible UI tests, state that gap clearly.",
      "",
      "## Manual QA expectations",
      "- Provide practical manual checks agents should perform after changes.",
      "- Ground manual QA in the repo’s app structure, commands, UI routes, API routes, and risky areas.",
      "- Do not invent deployment or CI steps.",
      "- If available commands are limited, suggest manual checks that do not require unavailable tooling.",
      "",
      "## Existing test evidence",
      "- Summarize detected test frameworks, test files, test folders, and test-related commands from the provided context.",
      "- Mention available commands from repo context exactly as provided.",
      "- Do not invent commands.",
      "- If no tests or test commands are detected, say so clearly.",
      "- Explain what the existing evidence does and does not prove.",
      "",
      "## Testing gaps and unknowns",
      "- List missing or weakly evidenced testing areas.",
      "- Include unknowns about test frameworks, test coverage, test types, CI, fixtures, integration tests, UI tests, manual QA, or team conventions when evidence is absent.",
      "- Phrase unknowns as practical warnings for future coding agents.",
      "",
      "## Things agents should avoid",
      "- List testing-related mistakes agents should avoid in this repo.",
      "- Examples: inventing unavailable test commands, adding a new test framework without explicit request, writing brittle tests disconnected from existing patterns, skipping verification for risky domain changes, or claiming coverage that does not exist.",
      "- Ground each avoid-rule in repo evidence or explicit unknowns.",
      "",
      "Style requirements:",
      "- Be concise and practical.",
      "- Use bullets where useful.",
      "- Use labels like `Observed:`, `Evidence:`, `Recommendation:`, and `Unknown:`.",
      "- Reference real file paths in backticks.",
      "- Mention commands exactly as they appear in repo context.",
      "- Avoid generic filler.",
      "- Avoid confident claims without file evidence.",
      "- Do not include code blocks unless absolutely necessary.",
      "",
      "# Grounding rules",
      formatGroundingRules(),
      "",
      "# Output rules",
      formatMarkdownOutputRules(),
      "",
      "# Repo context",
      formatKnowledgeDocContext(input),
    ].join("\n"),
  };
}
