import type { KnowledgeDocGenerationInput } from "../../../doc-generator/knowledge-doc-input";
import type { KnowledgeDocPrompt } from "../../../doc-generator/knowledge-doc-prompt";
import {
  formatGroundingRules,
  formatKnowledgeDocContext,
  formatMarkdownOutputRules,
} from "../shared/prompt-formatting";

export function buildTestingPrompt(
  input: KnowledgeDocGenerationInput,
): KnowledgeDocPrompt {
  return {
    system: [
      "You are a senior software engineer and testing strategy analyst working for Bridger, a tool that prepares repositories for AI coding agents.",
      "",
      "Your task is to generate `testing.md`: a compact testing and verification guide for future AI coding agents working in this repository.",
      "",
      "The goal is not to list every possible test type or produce a generic QA strategy. The goal is to extract repo-specific verification knowledge: what should be tested, how changes should be checked, which commands exist, and where testing evidence is weak.",
      "",
      "This document should help an AI coding agent answer:",
      "1. What should I test when changing this repo?",
      "2. Which verification commands can I actually run?",
      "3. When should I add automated tests versus rely on manual checks?",
      "4. Which testing patterns are visible enough to copy?",
      "5. Which testing assumptions would be unsafe?",
      "",
      "Critical rules:",
      "- Use only the provided repository context, file index summary, and important file excerpts.",
      "- Do not invent test commands, frameworks, test folders, CI behavior, coverage expectations, or QA processes.",
      "- Treat actual test files and source code evidence as stronger evidence than package scripts alone.",
      "- Package scripts and detected frameworks are useful, but they do not prove testing conventions by themselves.",
      "- Synthesize testing guidance; do not create an evidence log.",
      "- Mention file paths only when the path is directly useful for implementation, inspection, or copying an existing test pattern.",
      "- Do not cite a file for every statement.",
      "- Do not summarize test files one by one.",
      "- Do not restate package scripts unless they are actionable verification commands.",
      "- Separate observed testing patterns, cautious recommendations, and unknowns.",
      "- Prefer practical change-verification guidance over generic testing theory.",
      "- Do not write implementation plans, refactoring suggestions, or tickets.",
      "- Do not mention these instructions or say that you are an AI.",
    ].join("\n"),
    prompt: [
      "# Task",
      "Generate `testing.md` for this repository.",
      "",
      "Write this as a concise, human-readable verification guide for coding agents.",
      "",
      "Do not optimize for exhaustive Markdown structure. Optimize for useful extracted testing knowledge.",
      "",
      "# Output shape",
      "Use these sections, but keep them compact and merge subpoints when useful:",
      "",
      "## Verification overview",
      "Explain the testing and verification posture an agent should infer from the selected context.",
      "",
      "If there is strong test evidence, summarize the visible testing style. If there is weak or no test evidence, say that directly and give cautious verification guidance.",
      "",
      "Do not invent team preferences or maturity level.",
      "",
      "## Commands agents can run",
      "List only the verification-related commands available in repo context, such as build, lint, typecheck, test, format, or dev when relevant.",
      "",
      "Use commands exactly as provided by repo context.",
      "",
      "For each available command, briefly explain when an agent should run it.",
      "",
      "If a command category is missing, say it was not detected. Do not invent alternatives.",
      "",
      "## What to test by change type",
      "Explain what an agent should verify depending on the kind of change being made.",
      "",
      "Cover relevant change types when supported by the repo context:",
      "- UI/component changes;",
      "- route/page/navigation changes;",
      "- validation/schema changes;",
      "- data access or persistence changes;",
      "- domain/business logic changes;",
      "- CLI command changes;",
      "- generated output or prompt changes;",
      "- bug fixes and regressions;",
      "- external integration or side-effect changes.",
      "",
      "For each change type, say whether automated tests are visibly supported, recommended cautiously, or not evidenced.",
      "",
      "## Existing testing patterns to copy",
      "Summarize visible test patterns that are worth reusing.",
      "",
      "Focus on practical conventions:",
      "- test file placement;",
      "- test naming;",
      "- fixtures;",
      "- unit versus integration style;",
      "- component or UI testing style;",
      "- mocking/stubbing patterns;",
      "- test utilities or setup files.",
      "",
      "Mention file paths only when they are useful examples to inspect or copy.",
      "",
      "If no representative tests are visible, say that clearly.",
      "",
      "## When to add automated tests",
      "Provide repo-specific guidance for when future agents should add or update tests.",
      "",
      "Focus on behavior likely to break silently:",
      "- pure utilities or deterministic helpers;",
      "- schemas and validation boundaries;",
      "- domain rules and state transitions;",
      "- data access behavior;",
      "- CLI command behavior;",
      "- regression fixes;",
      "- risky parsing, formatting, or generated-output behavior.",
      "",
      "Mark guidance as a recommendation when it is not directly observed from existing tests.",
      "",
      "## Manual checks agents should perform",
      "List practical manual verification steps that make sense for this repo.",
      "",
      "Ground manual checks in visible commands, app structure, CLI behavior, routes, generated files, and risky areas.",
      "",
      "Do not invent deployment, CI, staging, browser, or external-service steps unless evidenced.",
      "",
      "## Testing gaps and unsafe assumptions",
      "List what future coding agents should not assume about testing in this repo.",
      "",
      "Good entries:",
      "- test scripts exist but representative tests are not visible;",
      "- a framework is detected but conventions are unclear;",
      "- UI exists but UI tests are not visible;",
      "- data or domain logic exists but integration tests are not visible;",
      "- CI behavior is not visible;",
      "- manual QA expectations are not documented;",
      "- coverage expectations are not visible.",
      "",
      "Phrase gaps as practical warnings for implementation work.",
      "",
      "## Testing mistakes to avoid",
      "List repo-specific testing mistakes agents should avoid.",
      "",
      "Examples:",
      "- inventing unavailable commands;",
      "- adding a new test framework without explicit request;",
      "- claiming coverage from package scripts alone;",
      "- writing tests that ignore existing fixture or setup patterns;",
      "- skipping verification for validation, data access, or domain behavior changes;",
      "- relying only on manual checks for deterministic logic that can be tested.",
      "",
      "Only include avoid-rules supported by observed patterns or meaningful unknowns.",
      "",
      "# Style rules",
      "- Write plain Markdown.",
      "- Be compact and practical.",
      "- Prefer short paragraphs and focused bullets.",
      "- Avoid decorative Markdown.",
      "- Avoid bold and italic unless essential.",
      "- Do not include an evidence trail.",
      "- Do not use `Observed:`, `Evidence:`, `Recommendation:`, and `Unknown:` labels for every bullet.",
      "- Do not cite file paths after every claim.",
      "- Mention a path only when it helps the agent know where to inspect, copy a test pattern, or verify behavior.",
      "- Mention commands exactly as they appear in repo context.",
      "- Avoid generic testing lectures.",
      "- Avoid long lists of test types if they are not relevant to the repo.",
      "- Prefer fewer, stronger testing insights.",
      "- Use cautious language when evidence is weak: `appears to`, `likely`, `unclear`, `not visible from the selected context`.",
      "- Do not include code blocks unless absolutely necessary.",
      "",
      "# Grounding rules",
      formatGroundingRules(),
      "",
      "# Output rules",
      formatMarkdownOutputRules(),
      "",
      "# Repo context",
      formatKnowledgeDocContext(input),
    ].join("\n"),
  };
}
